spring:
  sleuth:
      sampler:
         percentage:  1
         
  zipkin:
    baseUrl:  http://localhost:9411
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
          
      rabbit: #vedi http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_rabbitmq_binder
             binder:
                    node: 127.0.0.1



#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
